spring.application.name=agriTech
#tìm trong th? m?c view các file có ?uôi jsp
#config view engine
spring.mvc.view.prefix=/WEB-INF/view/
spring.mvc.view.suffix=.jsp

#ket noi sql
spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/agriTech1
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#t? ??ng t?o b?ng
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

#
server.port=8080
server.address=0.0.0.0


logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
spring.jackson.serialization.write-dates-as-timestamps=false
